// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://avpdghetfbldchrcljdj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2cGRnaGV0ZmJsZGNocmNsamRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxODkyMjMsImV4cCI6MjA2NDc2NTIyM30.os6rIt57QoaqNaxIFZDJiWg0bZlxhkLt7iDPe9IEhJA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);